(defun solve (str)
  (let ((ans 0)
        (idx 1)
        (found nil))
    (dotimes (i (length str))
      (let ((c (aref str i)))
        (if (eq c '#\() (setf ans (+ ans 1)) (setf ans (- ans 1))))
      (if (and (not found) (eq ans -1)) (and (print idx) (setf found t)))
      (setf idx (+ idx 1)))
    (print ans)))
